[build]
  command = "npm start"
  functions = "functions/"
  publish = "/"

[dev]
  command = "npm start"
  functions = "functions/"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
